_message:
	@echo "available targets: setup deploy run log"

setup:
	npm install

deploy:
	node_modules/.bin/react-native run-android

run:
	node_modules/.bin/react-native start

log:
	node_modules/.bin/react-native log-android

.PHONY: _message setup deploy run log
